name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - gittest/api-dev
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          echo "PYTHONPATH is set to $PYTHONPATH"
          pytest --maxfail=1 --disable-warnings -q

      - name: Notify on failure (Slack or Email)
        if: failure()
        run: echo "❌ Tests failed - configure Slack/email here"

      - name: Notify on success (Slack or Email)
        if: success()
        run: echo "✅ Tests passed - configure Slack/email here"
